CREATE TABLE `integrationAudits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerOpenId` varchar(64) NOT NULL,
	`integration` enum('bitrix24') NOT NULL DEFAULT 'bitrix24',
	`entityType` enum('partnerLead','contact','company','deal','webhook') NOT NULL,
	`entityId` int NOT NULL,
	`operation` enum('create','sync','retry','pull','webhook') NOT NULL,
	`status` enum('pending','success','failed') NOT NULL DEFAULT 'pending',
	`requestPayload` text,
	`responsePayload` text,
	`errorMessage` text,
	`externalId` varchar(120),
	`retryOfAuditId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `integrationAudits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partnerLeads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerOpenId` varchar(64) NOT NULL,
	`fullName` varchar(160) NOT NULL,
	`companyName` varchar(180) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(64),
	`telegram` varchar(80),
	`region` varchar(160),
	`source` enum('website','club','referral','manual') NOT NULL DEFAULT 'website',
	`interestType` enum('retail','horeca','distribution','collaboration','other') NOT NULL DEFAULT 'other',
	`preferredContactMethod` enum('email','phone','whatsapp','telegram','any') NOT NULL DEFAULT 'any',
	`interestProducts` text,
	`notes` text,
	`syncStatus` enum('pending','success','failed','retried') NOT NULL DEFAULT 'pending',
	`syncAttemptCount` int NOT NULL DEFAULT 0,
	`lastSyncAt` timestamp,
	`lastSyncError` text,
	`bitrixContactId` varchar(64),
	`bitrixCompanyId` varchar(64),
	`bitrixDealId` varchar(64),
	`bitrixLeadId` varchar(64),
	`bitrixStageId` varchar(120),
	`assignedManagerId` varchar(64),
	`assignedManagerName` varchar(160),
	`nextActivityAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partnerLeads_id` PRIMARY KEY(`id`)
);
