CREATE INDEX `idx_badges_ownerOpenId` ON `achievementBadges` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_badges_type` ON `achievementBadges` (`badgeType`);--> statement-breakpoint
CREATE INDEX `idx_feedback_purchaseId` ON `animalFeedbackMessages` (`purchaseId`);--> statement-breakpoint
CREATE INDEX `idx_feedback_animalId` ON `animalFeedbackMessages` (`animalId`);--> statement-breakpoint
CREATE INDEX `idx_feedback_ownerOpenId` ON `animalFeedbackMessages` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_animalMedia_animalId` ON `animalMedia` (`animalId`);--> statement-breakpoint
CREATE INDEX `idx_ownerships_ownerOpenId` ON `animalOwnerships` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_ownerships_animalId` ON `animalOwnerships` (`animalId`);--> statement-breakpoint
CREATE INDEX `idx_ownerships_status` ON `animalOwnerships` (`ownershipStatus`);--> statement-breakpoint
CREATE INDEX `idx_animalPhotos_animalSlug` ON `animalPhotos` (`animalSlug`);--> statement-breakpoint
CREATE INDEX `idx_animals_ownerOpenId` ON `animals` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_animals_status` ON `animals` (`animalStatus`);--> statement-breakpoint
CREATE INDEX `idx_chatMessages_animalId` ON `chatMessages` (`animalId`);--> statement-breakpoint
CREATE INDEX `idx_chatMessages_ownerOpenId` ON `chatMessages` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_clubPosts_ownerOpenId` ON `clubPosts` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_clubPosts_category` ON `clubPosts` (`category`);--> statement-breakpoint
CREATE INDEX `idx_families_ownerOpenId` ON `families` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_checklists_purchaseId` ON `farmerChecklists` (`purchaseId`);--> statement-breakpoint
CREATE INDEX `idx_checklists_animalId` ON `farmerChecklists` (`animalId`);--> statement-breakpoint
CREATE INDEX `idx_checklists_ownerOpenId` ON `farmerChecklists` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_marketplaceItems_categoryId` ON `marketplaceItems` (`categoryId`);--> statement-breakpoint
CREATE INDEX `idx_purchases_ownerOpenId` ON `marketplacePurchases` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_purchases_animalId` ON `marketplacePurchases` (`animalId`);--> statement-breakpoint
CREATE INDEX `idx_purchases_itemId` ON `marketplacePurchases` (`itemId`);--> statement-breakpoint
CREATE INDEX `idx_productBatches_animalSlug` ON `productBatches` (`animalSlug`);--> statement-breakpoint
CREATE INDEX `idx_ratingSnapshots_ownerOpenId` ON `ratingSnapshots` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_ratingSnapshots_date` ON `ratingSnapshots` (`snapshotDate`);--> statement-breakpoint
CREATE INDEX `idx_users_email` ON `users` (`email`);--> statement-breakpoint
CREATE INDEX `idx_users_role` ON `users` (`role`);--> statement-breakpoint
CREATE INDEX `idx_users_deletedAt` ON `users` (`deletedAt`);--> statement-breakpoint
CREATE INDEX `idx_walletTx_ownerOpenId` ON `walletTransactions` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_walletTx_walletId` ON `walletTransactions` (`walletId`);--> statement-breakpoint
CREATE INDEX `idx_wallets_ownerOpenId` ON `wallets` (`ownerOpenId`);--> statement-breakpoint
CREATE INDEX `idx_wallets_familyId` ON `wallets` (`familyId`);