/**
 * Bitrix24 CRM constants for Sher Kozu integration.
 * Generated by setup-bitrix24-funnel.mjs on 2026-04-20.
 *
 * Main funnel: "Персональное фермерство" (category 1)
 * Renewal funnel: "Сопровождение и продление" (category 3)
 */

/* ─── Funnel (Deal Category) IDs ─────────────────────────── */
export const B24_CATEGORY_MAIN = 1;
export const B24_CATEGORY_RENEWAL = 3;

/* ─── Main Funnel Stages ─────────────────────────────────── */
export const B24_STAGE = {
  /** Клиент забронировал долю, ожидает звонка менеджера */
  NEW_REQUEST: "C1:NEW_REQUEST",
  /** Менеджер проводит консультацию */
  CONSULTATION: "C1:CONSULTATION",
  /** Реквизиты отправлены, ожидаем оплату */
  AWAITING_PAYMENT: "C1:AWAITING_PAYMENT",
  /** Оплата подтверждена */
  PAYMENT_RECEIVED: "C1:PAYMENT_RECEIVED",
  /** Настройка кабинета: продуктовый план, доставка, клуб */
  CABINET_SETUP: "C1:CABINET_SETUP",
  /** Контроль первой доставки */
  FIRST_DELIVERY: "C1:FIRST_DELIVERY",
  /** Успешная стадия: активный владелец (mapped to C1:WON) */
  ACTIVE_OWNER: "C1:WON",
  /** Провальная стадия: заморожен (mapped to C1:LOSE) */
  FROZEN: "C1:LOSE",
} as const;

/* ─── Renewal Funnel Stages ──────────────────────────────── */
export const B24_RENEWAL_STAGE = {
  /** Уведомление о скором окончании */
  RENEWAL_NOTICE: "C3:RENEWAL_NOTICE",
  /** Консультация по продлению */
  RENEWAL_CONSULT: "C3:RENEWAL_CONSULT",
  /** Ожидание оплаты продления */
  RENEWAL_PAYMENT: "C3:RENEWAL_PAYMENT",
  /** Успешно продлено (mapped to C3:WON) */
  RENEWED: "C3:WON",
  /** Отток (mapped to C3:LOSE) */
  CHURNED: "C3:LOSE",
} as const;

/* ─── Custom Deal Fields ─────────────────────────────────── */
export const B24_FIELD = {
  /** koza.vip ownership row ID */
  OWNERSHIP_ID: "UF_CRM_KOZA_OWNERSHIP_ID",
  /** Имя животного */
  ANIMAL_NAME: "UF_CRM_KOZA_ANIMAL_NAME",
  /** Тип: goat / sheep */
  ANIMAL_TYPE: "UF_CRM_KOZA_ANIMAL_TYPE",
  /** Доля в процентах */
  SHARE_PCT: "UF_CRM_KOZA_SHARE_PCT",
  /** Название тарифа */
  TARIFF: "UF_CRM_KOZA_TARIFF",
  /** Ссылка на профиль владельца на koza.vip */
  PROFILE_URL: "UF_CRM_KOZA_PROFILE_URL",
  /** koza.vip user ID (openId) */
  USER_ID: "UF_CRM_KOZA_USER_ID",
} as const;

/* ─── Mapping: koza.vip ownership status → B24 stage ─────── */
export const OWNERSHIP_STATUS_TO_B24_STAGE: Record<string, string> = {
  pending_payment: B24_STAGE.AWAITING_PAYMENT,
  active: B24_STAGE.ACTIVE_OWNER,
  expired: B24_STAGE.FROZEN,
  cancelled: B24_STAGE.FROZEN,

};

/* ─── Mapping: B24 stage → koza.vip ownership status ─────── */
export const B24_STAGE_TO_OWNERSHIP_STATUS: Record<string, string> = {
  [B24_STAGE.NEW_REQUEST]: "pending_payment",
  [B24_STAGE.CONSULTATION]: "pending_payment",
  [B24_STAGE.AWAITING_PAYMENT]: "pending_payment",
  [B24_STAGE.PAYMENT_RECEIVED]: "active",
  [B24_STAGE.CABINET_SETUP]: "active",
  [B24_STAGE.FIRST_DELIVERY]: "active",
  [B24_STAGE.ACTIVE_OWNER]: "active",
  [B24_STAGE.FROZEN]: "cancelled",
};
